### ISSUE TITLE
Some of the columns of bipartmod output are null when using the weighted formula.

### ISSUE THREAD

**Issue by geeklhem** [stouffer/rgraph#8]
It makes sense that the fourth column  (number of within-module links) would be null as the graph is bipartite. However when using the weighted version of the modularity, the fourth (number of egdes in the module) is also null. 

Example: 

``` bash
$ bipartmod -f women_w.dat 2> /dev/null
2 1 9 0 9 9.000000 0.000000 9.000000 --- 2
3 3 19 0 19 19.000000 0.000000 19.000000 --- 7 1 4
4 2 8 0 8 8.000000 0.000000 8.000000 --- 15 12
5 13 64 0 64 64.000000 0.000000 64.000000 --- 9 14 8 0 3 16 5 10 11 13 6 18 17
$ bipartmod -f women_w.dat -w 2> /dev/null
1 8 0 0 0 0.000000 0.000000 0.000000 --- 3 6 7 4 5 2 1 8
2 9 0 0 0 0.000000 0.000000 0.000000 --- 11 12 13 9 16 18 17 10 15
14 1 0 0 0 0.000000 0.000000 0.000000 --- 14

$ bipartmod -f women_w.dat -p 2> /dev/null
2 15 75 0 75 75.000000 0.000000 75.000000 --- 3 6 8 13 2 15 1 16 4 5 18 14 10 7 17
3 3 19 0 19 19.000000 0.000000 19.000000 --- 12 9 0
14 1 6 0 6 6.000000 0.000000 6.000000 --- 11
$ bipartmod -f women_w.dat -wp 2> /dev/null
1 6 0 0 0 0.000000 0.000000 0.000000 --- 5 3 4 6 2 1
3 6 0 0 0 0.000000 0.000000 0.000000 --- 14 9 10 13 12 11
4 2 0 0 0 0.000000 0.000000 0.000000 --- 8 7
```

(see #7 for the extra columns)

**Comment by geeklhem** [comment]
I think I found out why !

**1) In the simulated annealing:**
`SACommunityIdentBipart`  calls `MapPartToNet`
whereas 
`SACommunityIdentBipartWeighted` calls `MapPartToNetFast`

**2) In the mapping** 
`MapPartToNet`, defined in modules.c is described as "Given a partition and a network, set all the pointers and all the group and node attributes to the right values." `MapPartToNetFast` is a copy-paste of this function, described as `/* a la DB Stouffer */` ;-), with the part that actually updates `totlinks inlinks outlinks totlinksW inlinksW` and `outlinksW`commented out (but they are still reseted to 0). 

This function seems to be used only in `SACommunityIdentBipartWeighted`:

``` bash
rgraph$ grep -r "MapPartToNetFast" ./**/*.c
./src/bipartite.c:        MapPartToNetFast(part, binet->net1);
./src/bipartite.c:      MapPartToNetFast(part, binet->net1); /* MUST DO this after copying a part! */
./src/modules.c:MapPartToNetFast(struct group *part, struct node_gra *net)
```

**Comment by stouffer** [comment]
Ah yes, now I remember this.

Essentially, many of the calculations in `MapPartToNet` are unnecessary when optimizing weighted modularity but also costly in terms of time, so I cut them out in `MapPartToNetFast`. However, in order to get the right output at the end, we should run `MapPartToNet` on the best partition.

Is there an obvious place to do it before `SACommunityIdentBipartWeighted` terminates?

**Comment by geeklhem** [comment]
I added it after the end of the simulated annealing. It should be fixed. 

``` bash
$ bipartmod -f women_w.dat -pm 2> /dev/null
2 15 75 0 75 75.000000 0.000000 75.000000 --- 3 6 8 13 2 15 1 16 4 5 18 14 10 7 17
3 3 19 0 19 19.000000 0.000000 19.000000 --- 12 9 0
14 1 6 0 6 6.000000 0.000000 6.000000 --- 11
$ bipartmod -f women_w.dat -pmw 2> /dev/null
1 6 32 0 32 187.000000 0.000000 187.000000 --- 5 3 4 6 2 1
3 6 33 0 33 151.000000 0.000000 151.000000 --- 14 9 10 13 12 11
4 2 24 0 24 117.000000 0.000000 117.000000 --- 8 7
```
